

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Buzz Hub",
  description: "Buzz Hub app generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" data-theme="light" >
      <body className={inter.className}>
        <StoreProvider>
        <Header />
        <main className="container">{children}</main>
        <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
